### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Goutam-NB** [Jebaitedneko/android_kernel_10or_G#1]
Non treble kernel  1.3
Wifi not working
Hotspot not working

**Comment by Jebaitedneko** [comment]
Not a kernel bug. Kernel is fully working in all aspects.
Kernel uses latest PRIMA WLAN drivers which the non-treble rom doesn't support since it's using very old signed drivers.
10or has not released the drivers they used and since the non-treble roms use signature verification, nothing much can be done about it.
